### ISSUE TITLE
Wozu sind die Dateien Diskpart.ps1 und NewDisk.ps1

### ISSUE THREAD

**Issue by Frank-Geisler** [AzureBoost/AzureBlackMagicWorkshop#1]
Hallo Tillmann!

Wozu brauchen wir die Dateien Diskpart.ps1 und NewDisk.ps1? Das sind die Dateien die als Custom Extension ausgeführt werden richtig? Macht es Sinn die in ein eigenes Verzeichnis zu packen? Die liegen momentan etwas komisch in der Gegend rum.

VG

Frank

**Comment by DiHo78** [comment]
Hallo Ihr zwei,

für mich lesen sich die Dateien in der Tat als Custom Extensions. Einfach in einen separaten Ordner packen würde ich sagen. Keep it smooth and simple.

Gruß
Dirk

**Comment by Frank-Geisler** [comment]
Hallo Dirk!

War eher ne Frage an @TEitelberg . Ich habe das jetzt aufgeräumt und jetzt sollte klar sein, dass das Custom Script Extensions sind.

Viele Grüße und vielen Dank

Frank
