### ISSUE TITLE
Frage / Anregung zu Diskpart.ps1

### ISSUE THREAD

**Issue by DiHo78** [AzureBoost/AzureBlackMagicWorkshop#6]
Hallo zusammen,

ich hab gerade einen kurzen Blick auf das Diskpart.ps1 script geworfen. 
Ist ja straight Forward und funktioniert auch.
Die Frage ist nur: muss man oder will man hier bei den Platten ggf. auch etwas Ordnung halten?  Es kann ja durchaus sein, dass die Disk 2-6, die man per diskpart anspricht, nicht zwingend auch die LUNs in der entsprechenden Reihenfolge sind.  Will sagen: der Bereich
create volume stripe disk=3,4,5 
52 format fs=NTFS Label='Data' UNIT=65536 QUICK 
53 assign letter=G 

stellt nicht sicher, dass die dahinterliegenden VHDs auch die VHDs 3,4, und 5 sind.  

Wie gesagt, ich weiß nicht, ob man darauf zwingend Wert legen muss.

Man könnte das Ganze auch rein in PowerShell lösen und StoragePools anlegen.
Hier hätte man dann auch die Möglichkeit, die Platten nach Ihrer PhysicalLocation zu sortieren und dann zuzuweisen.

Ich guck mal, ob ich Euch ein Beispiel einstelle.

Gruß
Dirk

**Comment by TEitelberg** [comment]
Hi Dirk,

Danke für dein Feedback. 

Als kleiner Hinweis, den Scripten ohne unsere Sessions fehlt ggf. nen bisschen Context. Den DiskPart Teil stellen wir als einen möglichen Weg vor und verweisen darauf, dass das eigentliche DiskPart im Projekt dynmaisch via PowerShell erzeugt wurde. 

Das mit den LUNS ist ein richtiger Hinweis, dadurch das wir die gesamte Umgebung aber in einem Stück hochfahren, können wir an Stelle mehr oder weniger sicher sein, dass das dies für diese Scripte so zutrifft.
Ein Beispiel Script wie man es mit PowerShell machen könntet, findest du im NewDisk.ps1 Script, auch wen dass Script nicht die Funktionen bietet die wir im Diskpart implementiert haben.

Wenn du ein schönes Beispiel hast, würden wir uns freuen es aufzunehmen.

VG,

Tillmann

**Comment by DiHo78** [comment]
Hiho,

ihr könnt Euch das ja mal anschauen und ggf. weiter verarbeiten. Ist nur ein wenig SpaghettiCode und ein wenig mit dem Sort-Object getrickst, um die ersten Platten bzgl. LUN Position zu bestimmen

[storagepoolBeispiel_Dirk.txt](https://github.com/AzureBoost/AzureBlackMagicWorkshop/files/2053118/storagepoolBeispiel_Dirk.txt)

Gruß
Dirk

**Comment by Frank-Geisler** [comment]
Hallo zusammen!

Erstmal vielen Dank an Dirk für den Hinweis und den Code. Ich schaue mal, dass ich das hier einarbeite (@DiHo78: Du kannst auch einfach selbst pushen und wir entscheiden dann ob wir den Code aufnehmen oder nicht - nur so fürs nächste Mal;)). Grundsätzlich ist es aber (mein Verständnis) ohnehin so, dass man heutzutage eher Storage Pools nehmen sollte statt Diskpart, weil Diskpart old fashioned ist und Stprage Pools viel mehr Möglichkeiten als dynamische Disks bieten. 

Viele Grüße

Frank

**Comment by Frank-Geisler** [comment]
Hallo zusammen!

Script gefällt  mir gut, habe ich mit aufgenommen.

Viele Grüße

Frank
